- name: Install Java (required by Kafka)
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes
  become: true

- name: Create Kafka installation directory
  file:
    path: /opt/kafka
    state: directory
    mode: "0755"
  become: true

- name: Create Kafka data directory
  file:
    path: /data/kafka
    state: directory
    owner: "{{ ansible_user | default('ubuntu') }}"
    group: "{{ ansible_user | default('ubuntu') }}"
    mode: "0755"
  become: true

- name: Download Kafka
  get_url:
    url: https://archive.apache.org/dist/kafka/3.6.0/kafka_2.13-3.6.0.tgz
    dest: /tmp/kafka.tgz
  become: true

- name: Extract Kafka
  unarchive:
    src: /tmp/kafka.tgz
    dest: /opt/kafka
    remote_src: yes
    extra_opts: [--strip-components=1]
  become: true

- name: Deploy Kafka server.properties
  template:
    src: server.properties.j2
    dest: /opt/kafka/config/server.properties
    owner: "{{ ansible_user | default('ubuntu') }}"
    group: "{{ ansible_user | default('ubuntu') }}"
    mode: "0644"
  become: true

- name: Set Kafka heap size in kafka-server-start.sh
  lineinfile:
    path: /opt/kafka/bin/kafka-server-start.sh
    regexp: "^KAFKA_HEAP_OPTS="
    line: 'export KAFKA_HEAP_OPTS="-Xmx16G -Xms16G"'
    insertafter: BOF
    backup: yes
  become: true

- name: Copy kafka.service to systemd
  copy:
    src: kafka.service
    dest: /etc/systemd/system/kafka.service
    mode: "0644"
  become: true

- name: Reload systemd and start Kafka service
  systemd:
    name: kafka
    enabled: true
    state: restarted
    daemon_reload: true
  become: true
